# Основные настройки
title: "Авантеко Стандартизация"
author: "Проектный отдел ООО МРЦ Авантеко"
#logo: "logo.png"

# Язык и кодировка
language: ru
encoding: utf-8

# Использование MyST
parse:
  myst_enable_extensions:
    - dollarmath
    - colon_fence
    - tasklist
    - deflist

# HTML настройки
html:
  #favicon: "favicon.ico"
  baseurl: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true

